# Generated by Django 6.0.4 on 2026-04-24 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of the related Payout or Payment', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='merchants.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'transaction_type'], name='ledger_ledg_merchan_55b3ff_idx'), models.Index(fields=['reference_id'], name='ledger_ledg_referen_a7e39d_idx')],
            },
        ),
    ]
